### ISSUE TITLE
Manually going to group edit page forces logout

### ISSUE THREAD

**Issue by RandomlyKnighted** [OpenHuntsville/hntsvll#108]
I've had this happen to me multiple times. I log in, I click the address part at the top of the browser, type in the URL for the group's edit page, hit enter and get a Pakyow error. When I look at the navigation bar it shows that I've been logged out.

**Comment by RandomlyKnighted** [comment]
Ok so after further investigation it looks like this only happens if you go to an invalid url (i.e. `/groups/cwn/edit` instead of `groups/2/edit`. While this isn't bad it still probably shouldn't log the user out. It should just show the error and you should be able to continue to navigate through the site.

**Comment by davidhjones** [comment]
The issue here is that when we hit an error page we're not updating the navigation bar to reflect that the user is still logged in.

**Comment by davidhjones** [comment]
Tightly coupled to bug #107
