### ISSUE TITLE
Hide stack trace errors before going live

### ISSUE THREAD

**Issue by RandomlyKnighted** [OpenHuntsville/hntsvll#109]
Currently, if Pakyow gives shows a stacktrace when it encounters an error. This should be hidden before we go live. If the error is not one of the normal 20x, 30x, 40x, or 50x errors then it should just give a generic error saying to contact a site administrator.

**Comment by davidhjones** [comment]
Test further. This may just be an issues on local instances

**Comment by davidhjones** [comment]
Confirmed. Stack trace is not shown in prod like it is in dev.
