### ISSUE TITLE
Categories show users who have not opted in

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#125]

**Comment by skylenewman** [comment]
This is not fixed.

On Feb 23, 2017 6:19 PM, "davidhjones" <notifications@github.com> wrote:

Closed #125 <https://github.com/OpenHuntsville/hntsvll/issues/125>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHuntsville/hntsvll/issues/125#event-975329657>, or mute
the thread

**Comment by skylenewman** [comment]
At least on production

**Comment by davidhjones** [comment]
Yeah it's only fixed on the dev branch. Maybe I'm doing this wrong? I've been fixing all the issues on the dev branch with the intention of a big PR merge to master fixing multiple issues. Should I be creating a new branch for every issue and submitting a PR to merge into master?

**Comment by RandomlyKnighted** [comment]
That'd the way a lot of projects do it. A branch/PR per feature/bug fix.

**Comment by davidhjones** [comment]
That just seems like so much overhead for me to fix a small defect. I can justify doing so for large issues but small issues it doesn't make sense. Maybe creating a branch for 4-5 small issues makes sense. Thoughts? Maybe we should take this to the Slack channel?
