### ISSUE TITLE
Deleting a group

### ISSUE THREAD

**Issue by tylerbhughes** [OpenHuntsville/hntsvll#129]
Currently, there is no way to delete a group once it has been created. It would be a good if this feature was added. At minimum it could be added for site admins.

Use Case: There is currently a AngularJS and ReactHSV groups. As of March 8th these will be one group. It would be nice if I could rename one group and then delete the other one.

**Comment by davidhjones** [comment]
Keep in mind that Events have a relationship to Groups. Each Event has a `group_id` attribute. Therefore, if you delete a group you must remove all the Events for that group, otherwise you'll have orphaned events.

**Comment by skylenewman** [comment]
I would be more in favor of archive type boolean. That way, the data is
still there and useful in the future.

**Comment by RandomlyKnighted** [comment]
I like @skylenewman's idea.  If we delete the event then there's no record that a past event ever happened. I'd much rather have an archive of past events whether or not the event still exists.

**Comment by davidhjones** [comment]
Yeah thats a good solution. We would still want to archive the events that fall under a given group, but I could see some value in persisting the data.

**Comment by tylerbhughes** [comment]
Events now archived when the user clicks the delete button. In order to archive the groups we'll need to do the following:

1. Add an "archived" column to the group table (set a default value of false
2. Add a delete button to the Edit Group page
3. Add a route for the delete button so that when the button is pressed it will update the value for the archived column to be set to true
4. Update the /groups route so it only shows groups that have archived set to false

Now one thing to note is that we're adding an archived functionality but we're not adding a way to go back and pull them back in. In order to un-archive a group or event we'd have to update the database manually.

**Comment by tylerbhughes** [comment]
Groups are now able to be archived. Currently this functionality is limited to site admins only.
