### ISSUE TITLE
Events show up in groups list

### ISSUE THREAD

**Issue by RandomlyKnighted** [OpenHuntsville/hntsvll#130]
I went to `/groups` and after a couple pages I noticed some of the events were showing up in the list. This should be fixed soon!

**Comment by davidhjones** [comment]
This is working as designed. We seeding the list of groups and events from the CWNSchedule spreadsheet. (https://docs.google.com/spreadsheets/d/1cNePpbnqO0slG7FNyGD08EEJv-ihjp3KPSD-IRejrAw/edit#gid=1586973828) In the spreadsheet the Visual Studio Launch Event (event) has the Visual Studio Launch Event (as a group)

**Comment by davidhjones** [comment]
@RandomlyKnighted is this safe to close?
