### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#36]
Adding gamification to the site.  

https://captainup.com/.

What does this even mean?

**Comment by chrisbeaman** [comment]
IMO this is irrelevant/invalid without further clarification.

**Comment by skylenewman** [comment]
Dutch suggested we use it to gamification-ize the site. It looks _neat_, but I don't know if cost/benefit is worth it.

**Comment by chrisbeaman** [comment]
Gamifaction-ize = gamify. I don't want to do this right now, maybe in iterations 2 or 3. I'll add it to the product roadmap: https://docs.google.com/spreadsheets/d/14sEHwZqO8ZePawQf35EoIZCmptpOIStz8TYWSec5WpY/edit#gid=0
