### ISSUE TITLE
Modify Categories

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#37]
# List of suggestions

## Review before making changes

+ Marketing
  - Event Logistics
  - meeting planning
+ IT
  - cabling
  - support
  - networking
+ Software
  - web
  - mobile
  - embedded
  - systems
  - applications
  - user experience
+ Health and Wellness
+ Proposals
  - Proposal Management
  - Proposal Writing
  - ~~Government Proposals~~
  - ~~Proposal Coordination~~
  - Proposal Strategy
+ Architecture
  - Urban Planning
  - Site Design
  - zoning research
  - zoning appeals
  - transportation planning
  - Demographic research
+ Business Development

**Comment by chrisbeaman** [comment]
This looks good to me, @skylenewman, however I would put "user experience" into the Design parent category.
