### ISSUE TITLE
Missing brackets

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#38]
From the console it looks like a missing > or two 
Check out your /about page on FF small issue on the small width desktop breakpoint

**Comment by chrisbeaman** [comment]
@skylenewman Where? What does this affect?

**Comment by skylenewman** [comment]
I'm not sure. We received feedback submission on it.

It affects HTML validation.

**Comment by chrisbeaman** [comment]
@skylenewman My HTML validator on Chrome says that the "About" page is valid
