### ISSUE TITLE
Investigate 'No slash ("/") between "IT and Software" and "Art and Design"'

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#42]
This is super trivial, but I just noticed that there is no slash between the categories "IT and Software" and "Art and Design" on my profile here: https://www.openhuntsville.com/categories/it-and-software - I wonder why

**Comment by chrisbeaman** [comment]
This happens with a bunch of categories actually.

**Comment by tylerbhughes** [comment]
The slash is hard to see but this appears to be fixed.
