### ISSUE TITLE
Extra menu element on Everyone page

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#44]

**Comment by chrisbeaman** [comment]
I assume this is talking about the half-gray box that is at the very bottom of the white sidebar? @skylenewman Did you mention you thought of another way to hide this?

**Comment by skylenewman** [comment]
Yes. We could hide it with CSS (or JS). I vote CSS.

**Comment by skylenewman** [comment]
If I don't have it already, I should add a class with URL slug to `body` element.
