### ISSUE TITLE
Create Profile bug on IE

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#46]
Create Profile page: The "We Make, Design, etc." quote shows up as a block of gradient instead of font as gradient - may not be fixable in IE (ACK I HATE IE)

**Comment by chrisbeaman** [comment]
Couple answers to this: http://www.webdesignerwall.com/demo/css-gradient-text/ , http://stackoverflow.com/questions/10165412/how-to-apply-webkit-gradient-to-ie

**Comment by tylerbhughes** [comment]
This is also happening with Firefox. I've created the following StackOverflow issue to try and solve the problem. 

https://stackoverflow.com/questions/45667465/gradient-is-being-applied-to-background-instead-of-text-in-ie-and-firefox

**Comment by tylerbhughes** [comment]
I posted an answer to my StackOverflow question showing the code that @drewmcdowell gave me that fixes the issue.
