### ISSUE TITLE
About Us image alignment

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#48]
I know you mentioned this in your post Chris but the About us page on desktop is not horizontally aligning the three "draft" images. Also do we need to use a higher resolution version of those images. I can reduce compression on them.

**Comment by chrisbeaman** [comment]
Yeah, need to do a little more work on this. However, each time I load the About page (both on my computer and in my IE9 emulator), the columns are vertically aligned for me. It's only when I start resizing my browser that they are off.

**Comment by skylenewman** [comment]
I've never really noticed anyone who wasn't a web designer resize their browser over and over.
