### ISSUE TITLE
No hero image

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#49]
There was no hero image behind "What's in a name?" on about us page.

**Comment by chrisbeaman** [comment]
@skylenewman there wasn't supposed to be a hero image behind "What's in a name?" Joe may have had one in his mockup, but this part of the mockup didn't follow the site styles with regard to how we have the breadcrumbs set up. Is this what you were referencing?

**Comment by skylenewman** [comment]
@chris that was copy/paste from Joe's Wunderlist item, so I assume so

**Comment by ProfessorTom** [comment]
Since Chris said above that the hero image was in the mockup only and doesn't match the design for the website, I'm closing this ticket.
