### ISSUE TITLE
Menu alignment issue in IE

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#50]
Create Profile page the "Get started" button and Terms of service are not aligned in IE. Maybe they should be left justified.

**Comment by chrisbeaman** [comment]
@skylenewman not sure I understand what you mean. I am using http://netrenderer.com/index.php to test in IE and according to this tool's IE9 test, the "By clicking 'Get started!'" text is left aligned below the "Get Started!" button, which is how it's supposed to be.

**Comment by skylenewman** [comment]
This was a Wunderlist item from Joe.
