### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#52]

**Comment by chrisbeaman** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66145632-2', 'auto');
  ga('send', 'pageview');

</script>

**Comment by chrisbeaman** [comment]
Tracking ID: UA-66145632-2

**Comment by chrisbeaman** [comment]
@skylenewman you just need to add the above to the site. The (script) tags need angle brackets.
