### ISSUE TITLE
Refactor views

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#67]

**Comment by ProfessorTom** [comment]
Can we get more description?

**Comment by skylenewman** [comment]
Nope. This is a Kyle issue.

**Comment by ProfessorTom** [comment]
Fair enough.

On Sat, Jul 9, 2016 at 3:36 PM, Kyle Newman <notifications@github.com>
wrote:

> Nope. This is a Kyle issue.
>
> On Jul 9, 2016 3:32 PM, "ProfessorTom" <notifications@github.com> wrote:
>
> > Can we get more description?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/OpenHuntsville/hntsvll/issues/67#issuecomment-231554461
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABY-YibInGs1CbTM7O5E8kiKTJ8jP0V1ks5qUAV4gaJpZM4JIsUN
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenHuntsville/hntsvll/issues/67#issuecomment-231554607>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADCK8NJtjY7kG-ELQhVjowm5jRQ8WmXiks5qUAZLgaJpZM4JIsUN>
> .
>



-- 
A programmer is a tool which converts caffeine to source code
