### ISSUE TITLE
Force correct URL format for website on profile edit page

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#69]
All URLs should have the full URL (including http/https)

Create a JS validator and Ruby validation code for that field.

No incorrect strings should be posted to back end, but in the case of noJS, etc. the backend should disregard incorrectly formatted strings.

This is an idea for front-end:
![gravityforms-websitefieldhttp2](https://cloud.githubusercontent.com/assets/1457762/17273036/2b3eb1ac-566d-11e6-9ae2-798f1f8a83e7.png)

**Comment by RandomlyKnighted** [comment]
One way this could be done is via the type and pattern attributes built into the input element. For example, the code below will only accept text starting with `http://` or `https://` and at least one additional character. 

```html
<input type="url" required pattern="https?://.+">
```

@skylenewman what do you think?

**Comment by skylenewman** [comment]
@RandomlyKnighted if that is the selected method, I would *definitely* want to have an approach on the server side, since this is not fully supported: http://www.w3schools.com/tags/att_input_pattern.asp

**Comment by davidhjones** [comment]
Also related to #128 . Might want to knock all 3 related issues out with one commit
