### ISSUE TITLE
Disallow editing of email address on profile edit screen

### ISSUE THREAD

**Issue by skylenewman** [OpenHuntsville/hntsvll#76]
**Edit: Additions italicized.**

Since emails are kind of a de facto unique id _on the web and we need to have an active email address on file_, we need for users to not be able to edit them _without first verifying that they are an active email address_. This means:
1. The email input on `app/views/people/_form.html` should have a `disabled` attribute.
2. In the case that someone knows how to use developer tools, the `action :update` route should disregard changes.
3. _Near the email input should be some kind of UI element (i.e. link, button) that sends users to a new page to change email._
4. _New page for changing email describes the process and inputs._

**_Process_**
1. _User enters the email address the user would like to use and clicks the "Change" button._
2. _The Ruby code persists the new email address without saving it to the user's database record._
3. _The Ruby code uses the Mailgun integration to send the user a code to verify that they have access to the email address._
4. _The user enters that code in a form to persist the email in the user's database record._

**_Implementation notes_**
- _To create the page, an HTML file will need to be created in `app/views/people`._
- _To be visible when deployed, the page will need a GET route._
- _The functionality should have simple forms and work without JS enabled. Using `data-ui="mutable"` should be a progressive enhancement._

**Edit: Additions italicized.**

**Comment by RandomlyKnighted** [comment]
What if someone changes their e-mail? For example, if someone signs up using their work e-mail and leaves their job they may want to update their account to an email address they can still access.

I have only used relational databases before and have never used PostgreSQL but shouldn't our unique id (Primary Key) be something that will never change? In all the projects I've dealt with in the past this is usually an integer that increments with each new row.

**Comment by skylenewman** [comment]
@RandomlyKnighted That's a good point. Technically, it's not a key, but I always equate emails with identity. I will update the issue.

**Comment by tylerbhughes** [comment]
We're already using the ID column in this table as a way to identify the user. That being said I believe this issue is no longer relevant.
