### ISSUE TITLE
Multiple search boxes when selecting a category

### ISSUE THREAD

**Issue by tylerbhughes** [OpenHuntsville/hntsvll#77]
When viewing the [People page](http://www.openhsv.com/people) there is only one search box.  However, when you click on one of the categories in the left sidebar you will then get 2 search boxes at the top of the page. 

![openhsv_search_boxes](https://cloud.githubusercontent.com/assets/2483249/18038091/b36c71b6-6d58-11e6-85c1-cf48acc294e4.PNG)

**Comment by skylenewman** [comment]
Thank you @RandomlyKnighted !

For anyone looking into this issue, the extra markup is in `app/views/categories/show.html`

**Comment by RandomlyKnighted** [comment]
Thanks @skylenewman. I was going to look into this later and submit a Pull Request fixing it.
